// Code generated by MCHP Chatbot
#ifndef TCP_SERVER_H
#define TCP_SERVER_H

#include "lwip/tcp.h"
#include <stdint.h>
#include <stdbool.h>

// Callback definition (tcp_server_config, payload, length)
typedef void (*tcp_server_recv_fn)(void* tcp_server_cfg, const uint8_t* data, uint16_t len);

typedef struct {
    uint16_t port;               // Port to listen on   
    struct tcp_pcb* pcb;         // Active connection PCB, do not fill this value
    tcp_server_recv_fn recv_fn;  // callback function to handle incoming data from client
} TCP_Server;

bool tcp_server_start(TCP_Server* cfg);
void tcp_server_stop(TCP_Server* cfg);
void tcp_server_send(TCP_Server* cfg, const uint8_t* data, uint16_t len);

#endif // TCP_SERVER_H